# Generated by Django 4.2.5 on 2023-09-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attack',
            field=models.IntegerField(default='0000000', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='item',
            name='defense',
            field=models.IntegerField(default='0000000', editable=False, max_length=7),
        ),
    ]
