# Generated by Django 4.2.5 on 2023-09-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_attack_alter_item_defense'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='connection',
            field=models.TextField(default='', editable=False),
        ),
    ]
