# Generated by Django 4.2.5 on 2023-09-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_date_added_alter_item_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='item',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='item',
            name='defense',
        ),
        migrations.AddField(
            model_name='item',
            name='omen',
            field=models.IntegerField(default=0),
        ),
    ]
