# Generated by Django 4.2.5 on 2023-09-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_item_attack_remove_item_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='space',
            field=models.IntegerField(default=0),
        ),
    ]
